# Generated by Django 5.0.6 on 2024-09-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_poster_url_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='synopsys',
            field=models.TextField(blank=True, null=True),
        ),
    ]
