# Generated by Django 5.0.6 on 2024-09-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_watchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'ordering': ['-watched_at']},
        ),
    ]
